name: Build Orchestrator Android App

on:
  workflow_call:
  workflow_dispatch:

env:
    DOTNETVERSION: 8.0.204
jobs:
  create_runner:
    name: Deploy Self Hosted Runner
    runs-on:
    - self-hosted
    - ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Pull VM
          id: pull
          uses: parallels/parallels-desktop-github-action@beta
          with:
            operation: 'pull'
            username: ${{ secrets.ORCHESTRATOR_USERNAME }}
            password: ${{ secrets.ORCHESTRATOR_PASSWORD }}
            orchestrator_url: devops.local-build.co
            base_image: http://root:${{ secrets.ORCHESTRATOR_PASSWORD }}@catalog.local-build.co/WINDOWS_11_DEVBOX/v1
            start_after_op: true
        - name: Configure Github Runner
          id: configure  
          uses: parallels/parallels-desktop-github-action@beta
          with:
            max_attempts: 5
            timeout_seconds: 2
            operation: 'run'
            username: ${{ secrets.ORCHESTRATOR_USERNAME }}
            password: ${{ secrets.ORCHESTRATOR_PASSWORD }}
            machine_name: ${{ steps.pull.outputs.vm_id }}
            run: |
                curl -o c:\install-runner.ps1 https://raw.githubusercontent.com/Parallels/prlctl-scripts/main/github/actions-runner/windows/install-runner.ps1
                curl -o c:\configure-runner.ps1 https://raw.githubusercontent.com/Parallels/prlctl-scripts/main/github/actions-runner/windows/configure-runner.ps1
                curl -o c:\remove-runner.ps1 https://raw.githubusercontent.com/Parallels/prlctl-scripts/main/github/actions-runner/windows/remove-runner.ps1

                powershell c:\install-runner.ps1
                powershell c:\configure-runner.ps1 -o Locally-build -t ${{ secrets.GH_PAT }} -n ${{ github.run_id }}_builder -l ${{ github.run_id }}_builder
    outputs:
        vm_id: ${{ steps.pull.outputs.vm_id }}
        vm_name: ${{ steps.pull.outputs.vm_name }}
  build_android:
    name: Build Android Apk
    needs: create_runner
    runs-on: 
        - self-hosted
        - Windows
        - ${{ github.run_id }}_builder

    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET SDK ${{env.DOTNETVERSION}}
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version:  '${{env.DOTNETVERSION}}'

        - name: List installed .NET info
          shell: pwsh
          run: dotnet --info

        - name: Install .NET MAUI
          shell: pwsh
          run: |
            dotnet nuget locals all --clear 
            dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
            dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json

        # - name: Restore nuget packages
        #   run: |
        #     dotnet restore weather_twenty_one_maui.sln

          # https://docs.microsoft.com/en-us/dotnet/maui/android/deployment/overview
        - name : Build Android App
          shell: pwsh
          run: |
            dotnet publish -f:net8.0-android -c:Release

        # - name: Build and Run UnitTests
        #   shell: bash
        #   run: |
        #     dotnet build <path to unit test csproj>
        #     dotnet test <path to unit test csproj> --no-build --verbosity normal

        - uses: actions/upload-artifact@v2
          with:
            name: artifacts-android
            path: |
              bin\Release\net8.0-android\publish\*.apk
  clean_runner:
    if: always()
    needs:
    - build_android
    - create_runner
    name: Clean Runner
    runs-on:
    - self-hosted
    - ubuntu-latest
    steps:
        - name: Remove Github Runner
          id: configure  
          uses: parallels/parallels-desktop-github-action@v1
          with:
            operation: 'run'
            username: ${{ secrets.ORCHESTRATOR_USERNAME }}
            password: ${{ secrets.ORCHESTRATOR_PASSWORD }}
            orchestrator_url: devops.local-build.co
            machine_name: ${{ needs.create_runner.outputs.vm_id }}
            run: |
                /Users/remove-runner.sh -u parallels -p /Users/action-runner -o Locally-build -t ${{ secrets.GH_PAT }}
        - name: Remove VM
          if: always()
          id: remove
          uses: parallels/parallels-desktop-github-action@v1
          with:
            operation: 'delete'
            username: ${{ secrets.ORCHESTRATOR_USERNAME }}
            password: ${{ secrets.ORCHESTRATOR_PASSWORD }}
            orchestrator_url: devops.local-build.co
            machine_name: ${{ needs.create_runner.outputs.vm_id }}