name: Build Android

on:
  workflow_call:
    inputs:
      upload_artifacts:
        type: boolean
        default: true
      run_tests:
        type: boolean
        default: true
      region:
        required: true
        type: string
        default: "eu-west-2"
jobs:
  Build:
    runs-on: [self-hosted, linux, ARM64]

    env:
        CONFIGURATION_SERVICES_WEBAPP_SERVICE_API_SUBDOMAIN: ""
        CONFIGURATION_SERVICES_WEBCLIENT_SERVICE_DOMAIN: ""
        FLUTTER_HOME: "${{ github.workspace }}/flutter"

    steps:
      - uses: actions/checkout@v2

      - name: Update Path
        run: |
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install Building Tools
        if: false
        run: |
          sudo apt install -y cmake clang ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - uses: cjlapao/setup-flutter-action@v0.1.6
        name: Setup Flutter
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Test
        if: ${{ inputs.run_tests == true }}
        run: flutter test

      - name: Build Android App Bundle
        run: flutter build linux --release

      #   - name: Build Android App Bundle
      #   run: flutter build appbundle --release --obfuscate --split-debug-info .

      - name: Upload Linux ARM64 Bundle Artifact
        if: ${{ inputs.upload_artifacts == true }}
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: build/linux/arm64/release/bundle