name: Build Linux Test

on:
  workflow_call:
  workflow_dispatch:

env:
    DOTNETVERSION: 8.0.204
jobs:
  create_runner:
    name: Deploy Self Hosted Runner
    runs-on: [self-hosted, ubuntu-latest]
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Clone VM
          id: pull
          uses: parallels/parallels-desktop-github-action@v1
          with:
            operation: 'clone'
            username: ${{ secrets.PARALLELS_USERNAME }}
            password: ${{ secrets.PARALLELS_PASSWORD }}
            insecure: true
            host_url: home.carloslapao.com:5470
            base_vm: ubuntu_action_runner_builder
            start_after_op: true
        - run: |
            echo "VM ID: ${{ steps.pull.outputs.vm_id }}"
            echo "VM Name: ${{ steps.pull.outputs.vm_name }}"
        - name: Configure Github Runner
          id: configure  
          uses: parallels/parallels-desktop-github-action@v1
          with:
            max_attempts: 5
            timeout_seconds: 2
            operation: 'run'
            username: ${{ secrets.PARALLELS_USERNAME }}
            password: ${{ secrets.PARALLELS_PASSWORD }}
            host_url: home.carloslapao.com:5470
            insecure: true
            machine_name: ${{ steps.pull.outputs.vm_id }}
            run: |
                curl -o c:\install-runner.ps1 https://raw.githubusercontent.com/Parallels/prlctl-scripts/main/github/actions-runner/windows/install-runner.ps1
                curl -o c:\configure-runner.ps1 https://raw.githubusercontent.com/Parallels/prlctl-scripts/main/github/actions-runner/windows/configure-runner.ps1
                curl -o c:\remove-runner.ps1 https://raw.githubusercontent.com/Parallels/prlctl-scripts/main/github/actions-runner/windows/remove-runner.ps1

                powershell c:\install-runner.ps1
                powershell c:\configure-runner.ps1 -o Locally-build -t ${{ secrets.GH_PAT }} -n ${{ github.run_id }}_builder -l ${{ github.run_id }}_builder
    outputs:
        vm_id: ${{ steps.pull.outputs.vm_id }}
        vm_name: ${{ steps.pull.outputs.vm_name }}
  clean_runner:
    if: always()
    needs: 
    - create_runner
    name: Clean Runner
    runs-on: ubuntu-latest
    steps:
        - name: Remove Github Runner
          id: configure  
          uses: parallels/parallels-desktop-github-action@v1
          with:
            operation: 'run'
            username: ${{ secrets.PARALLELS_USERNAME }}
            password: ${{ secrets.PARALLELS_PASSWORD }}
            host_url: home.carloslapao.com:5470
            insecure: true
            machine_name: ${{ needs.create_runner.outputs.vm_id }}
            run: |
                powershell c:\remove-runner.sh -o Locally-build -t ${{ secrets.GH_PAT }}
        - name: Remove VM
          if: always()
          id: remove
          uses: parallels/parallels-desktop-github-action@v1
          with:
            operation: 'delete'
            username: ${{ secrets.PARALLELS_USERNAME }}
            password: ${{ secrets.PARALLELS_PASSWORD }}
            insecure: true
            host_url: home.carloslapao.com:5470
            machine_name: ${{ needs.create_runner.outputs.vm_id }}