name: PR Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [main1]

jobs:
  create_runner:
    name: Create Self Hosted Runners
    uses: ./.github/workflows/deploy_runner.yaml
    secrets: inherit
    with:
      runner_name: weather-app-runner
      github_org_name: Locally-build/acme-weather-app
  build_linux:
    name: Linux
    if: false
    uses: ./.github/workflows/build_linux_arm.yaml
    needs: create_runner
    with:
      region: us-east-2
      run_tests: false
  build_ubuntu:
    name: Android
    if: false
    uses: ./.github/workflows/build_android.yaml
    needs: create_runner
    with:
      region: us-east-2
      run_tests: false
  build_ios:
    name: iOS
    if: false
    uses: ./.github/workflows/build_ios.yaml
    needs: create_runner
    with:
      region: us-east-2
