name: PR Validation

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main1

jobs:
  build_ios:
    name: IOS App
    if: false
    uses: ./.github/workflows/build_ios.yaml
  build_mac_catalysr:
    name: Mac Catalyst App
    if: false
    uses: ./.github/workflows/build_mac_catalyst.yaml

