name: PR Validation

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main

jobs:
  build_ios:
    name: iOS App
    uses: ./.github/workflows/build_ios.yaml
  build_mac_catalyst:
    name: Mac Catalyst App
    uses: ./.github/workflows/build_mac_catalyst.yaml
  build_android:
    name: Android Apk
    uses: ./.github/workflows/build_android.yaml
  build_windows:
    name: Windows msix
    uses: ./.github/workflows/build_windows.yaml

